### ISSUE TITLE
Icons are basically invisible in dark mode

### ISSUE THREAD

**Issue by Pustur** [chintan992/chintan992#1]
Hello,

Github recently added dark mode and I just wanted to let you know that your icons (in "how to reach me" and "skills") are basically invisible when this feature is turned on.

Here's a screenshot:
![screen](https://user-images.githubusercontent.com/13663338/101959515-c3a7f700-3c05-11eb-83f9-19ba6b87ddcd.png)

**Comment by chintan992** [comment]
I will fix it. Btw thanks for ping.😅
